apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-flask-app
  template:
    metadata:
      labels:
        app: python-flask-app
    spec:
      containers:
      - name: python-flask-app
        image: devops-project:latest  
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: python-flask-service
spec:
  selector:
    app: python-flask-app
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 8080 
  type: Nodeport



